name: Jupyter

on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:
  # Schedule the workflow to run every 24 hours
  schedule:
    - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute Jupyter Notebook
        run: |
          jupyter nbconvert --execute --to notebook --inplace webscraping_cryptocurrency.ipynb

      - name: Commit and Push Changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "GH ACTION Headlines $(date)"
          git push origin main

